version: '3.5'

services:

  app:
    container_name: app
    build:
      context: .
    volumes:
      - '.:/var/www'
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: